
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

POST_URL=https://ucb--tst2.custhelp.com/services/rest/connect/v1.3/
USERNAME=Developer5
PASSWORD=Developer1234
CONTACT_ID=1627016
#API_KEY=ucbT2N2Q8S282bDBelZ5kLjsmv1ThITc3mRoKjoJfpTYkjoypuSi7gUOwvJnJRjL

#Username = Developer3 
#Password = Developer1234 
#UrIUCB=http://localhost:8082/BotVirtual
#UrlUpdateUCB=https://ho0la347.unicreditgroup.ba:8443/BotVirtual
#instancaUCB=https://ucb--tst2.custhelp.com 
PROXY_PORT=8080
#certificatesTrustStorePath=C:/Program Files/Apache Software Foundation/Tomcat 9.0/certs/ho01a347.jks 
certificatesTrustStorePathCLOUD=C:/Program Files/Apache Software Foundation/Tomcat 9.0/certs/idcs-digicert-global-ca.jks 
PROXY=10.227.249.19 
TARGET=ucb--tst2.custhelp.com 
#interval = 1 
#frekvencija = MINUTES 
#test_patch_post = false
